# Generated by Django 5.1.3 on 2024-11-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqsection',
            options={'verbose_name': 'FAQ Section', 'verbose_name_plural': 'FAQ Sections'},
        ),
        migrations.AlterField(
            model_name='faqsection',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional - recommended to use an image with a transparent background.', null=True, upload_to='FaqSection/first_section_image/', verbose_name='First Section Image'),
        ),
        migrations.AlterField(
            model_name='faqsection',
            name='image_banner',
            field=models.ImageField(blank=True, help_text='Optional - you can upload an image or leave it blank. <br> If no image is selected, a default image will be displayed.', null=True, upload_to='FaqSection/image_banner/', verbose_name='Image Banner'),
        ),
    ]
