# Generated by Django 5.1.3 on 2024-11-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=255)),
                ('experience_years', models.PositiveIntegerField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('portfolio', models.FileField(blank=True, null=True, upload_to='portfolios/')),
                ('about', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
