# Generated by Django 5.1.3 on 2024-11-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner', models.ImageField(blank=True, help_text='Optional - you can upload an image or leave it blank. <br> If no image is selected, a default image will be displayed.', null=True, upload_to='Our_Services/Electricity/image_banner/', verbose_name='Image Banner')),
                ('title', models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='Title')),
                ('title_ar', models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Our_Services/Electricity/first_section_image/', verbose_name='First Section Image')),
            ],
            options={
                'verbose_name': 'electricity',
                'verbose_name_plural': 'electricity',
            },
        ),
    ]
