# Generated by Django 5.1.3 on 2024-11-27 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_jobinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobinfo',
            options={'verbose_name': 'Job Info', 'verbose_name_plural': 'Job Info'},
        ),
    ]
