# Generated by Django 5.1.3 on 2024-11-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner', models.ImageField(blank=True, help_text='Optional - as you like <br> If no image is selected, an automatic image appears.', null=True, upload_to='innovation/image_banner/', verbose_name='Image Banner ')),
                ('title_first_section', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='Title_first_section')),
                ('description_first_section', models.TextField(blank=True, help_text='Maximum characters 1000', max_length=1000, null=True, verbose_name='description_first_section')),
                ('image_first_section', models.ImageField(blank=True, help_text='It is preferable to use a blank image.', null=True, upload_to='Home_Page/Feature_icon/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Mechanics',
                'verbose_name_plural': ' Mechanics',
            },
        ),
    ]
