# Generated by Django 5.1.3 on 2024-11-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Our_Services', '0002_alter_mechanics_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanics',
            name='first_section_title_ar',
            field=models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='First Section Title'),
        ),
        migrations.AddField(
            model_name='mechanics',
            name='first_section_title_en',
            field=models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='First Section Title'),
        ),
    ]
