# Generated by Django 5.1.3 on 2024-11-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Our_Services', '0005_bodyworkandpainting_bodyworkandpaintingslider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodyworkandpainting',
            options={'verbose_name': 'BodyworkAndPainting', 'verbose_name_plural': 'BodyworkAndPainting'},
        ),
    ]
