# Generated by Django 5.1.3 on 2024-11-25 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Our_Services', '0006_alter_bodyworkandpainting_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodyworkandpaintingslider',
            old_name='mechanics',
            new_name='bodyworkandpainting',
        ),
        migrations.RenameField(
            model_name='electricityslider',
            old_name='mechanics',
            new_name='electricity',
        ),
    ]
