# Generated by Django 5.1.3 on 2024-11-26 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Our_Services', '0008_thermalandsoundinsulation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarProgramming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner', models.ImageField(blank=True, help_text='Optional - you can upload an image or leave it blank. <br> If no image is selected, a default image will be displayed.', null=True, upload_to='mechanics/image_banner/', verbose_name='Image Banner')),
                ('first_section_title', models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='First Section Title')),
                ('first_section_title_ar', models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='First Section Title')),
                ('first_section_title_en', models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='First Section Title')),
                ('first_section_description', models.TextField(blank=True, help_text='Description of the first section', null=True, verbose_name='First Section Description')),
                ('first_section_description_ar', models.TextField(blank=True, help_text='Description of the first section', null=True, verbose_name='First Section Description')),
                ('first_section_description_en', models.TextField(blank=True, help_text='Description of the first section', null=True, verbose_name='First Section Description')),
                ('first_section_image', models.ImageField(blank=True, help_text='Optional - recommended to use an image with a transparent background.', null=True, upload_to='mechanics/first_section/', verbose_name='First Section Image')),
                ('second_section_title', models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='Second Section Title')),
                ('second_section_title_ar', models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='Second Section Title')),
                ('second_section_title_en', models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='Second Section Title')),
                ('second_section_description', models.TextField(blank=True, help_text='Description of the second section', null=True, verbose_name='Second Section Description')),
                ('second_section_description_ar', models.TextField(blank=True, help_text='Description of the second section', null=True, verbose_name='Second Section Description')),
                ('second_section_description_en', models.TextField(blank=True, help_text='Description of the second section', null=True, verbose_name='Second Section Description')),
                ('second_section_image', models.ImageField(blank=True, help_text='Optional - recommended to use an image with a transparent background.', null=True, upload_to='mechanics/second_section/', verbose_name='Second Section Image')),
            ],
            options={
                'verbose_name': 'carprogramming',
                'verbose_name_plural': 'carprogramming',
            },
        ),
        migrations.AlterField(
            model_name='mechanics',
            name='first_section_image',
            field=models.ImageField(blank=True, help_text='Optional - recommended to use an image with a transparent background.', null=True, upload_to='Our_Services/Mechanics/first_section/', verbose_name='First Section Image'),
        ),
        migrations.AlterField(
            model_name='mechanics',
            name='image_banner',
            field=models.ImageField(blank=True, help_text='Optional - you can upload an image or leave it blank. <br> If no image is selected, a default image will be displayed.', null=True, upload_to='Our_Services/Mechanics/image_banner/', verbose_name='Image Banner'),
        ),
        migrations.AlterField(
            model_name='mechanics',
            name='second_section_image',
            field=models.ImageField(blank=True, help_text='Optional - recommended to use an image with a transparent background.', null=True, upload_to='Our_Services/Mechanics/second_section/', verbose_name='Second Section Image'),
        ),
        migrations.AlterField(
            model_name='thermalandsoundinsulationslider',
            name='thermalandsoundinsulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='Our_Services.thermalandsoundinsulation', verbose_name='thermalandsoundinsulation'),
        ),
        migrations.CreateModel(
            name='CarProgrammingSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(blank=True, help_text='Optional - you can upload an image or leave it blank. <br> If no image is selected, a default image will be displayed.', null=True, upload_to='mechanics/slider_images/', verbose_name='Slider Image')),
                ('carprogramming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='Our_Services.carprogramming', verbose_name='carprogramming')),
            ],
            options={
                'verbose_name': 'CarProgrammingSlider Slider',
                'verbose_name_plural': 'CarProgrammingSlider Sliders',
            },
        ),
    ]
