# Generated by Django 5.1.3 on 2024-11-26 13:47

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Our_Services', '0012_alter_roadsideassistance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanics',
            name='first_section_description',
            field=tinymce.models.HTMLField(blank=True, help_text='Description of the first section', null=True, verbose_name='First Section Description'),
        ),
        migrations.AlterField(
            model_name='mechanics',
            name='first_section_description_ar',
            field=tinymce.models.HTMLField(blank=True, help_text='Description of the first section', null=True, verbose_name='First Section Description'),
        ),
        migrations.AlterField(
            model_name='mechanics',
            name='first_section_description_en',
            field=tinymce.models.HTMLField(blank=True, help_text='Description of the first section', null=True, verbose_name='First Section Description'),
        ),
    ]
