# Generated by Django 5.1.3 on 2024-11-30 14:18

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Our_Services', '0013_alter_mechanics_first_section_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodyworkandpainting',
            options={'verbose_name': '3 - BodyWork And Painting', 'verbose_name_plural': '3 - BodyWork And Painting'},
        ),
        migrations.AlterModelOptions(
            name='carprogramming',
            options={'verbose_name': '5 - Car Programming', 'verbose_name_plural': '5 - Car Programming'},
        ),
        migrations.AlterModelOptions(
            name='electricity',
            options={'verbose_name': '2 - Electricity', 'verbose_name_plural': '2 - Electricity'},
        ),
        migrations.AlterModelOptions(
            name='mechanics',
            options={'verbose_name': '1 - Mechanic', 'verbose_name_plural': '1 - Mechanics'},
        ),
        migrations.AlterModelOptions(
            name='roadsideassistance',
            options={'verbose_name': '7 - Roadside Assistance', 'verbose_name_plural': '7 - Roadside Assistance'},
        ),
        migrations.AlterModelOptions(
            name='sportssuspension',
            options={'verbose_name': '6 - Sports Suspension', 'verbose_name_plural': '6 - Sports Suspension'},
        ),
        migrations.AlterModelOptions(
            name='thermalandsoundinsulation',
            options={'verbose_name': '4 - Thermal And Sound Insulation', 'verbose_name_plural': '4 - Thermal And Sound Insulations'},
        ),
        migrations.AlterField(
            model_name='bodyworkandpainting',
            name='first_section_description',
            field=tinymce.models.HTMLField(blank=True, help_text='Description of the first section', null=True, verbose_name='First Section Description'),
        ),
        migrations.AlterField(
            model_name='bodyworkandpainting',
            name='first_section_description_ar',
            field=tinymce.models.HTMLField(blank=True, help_text='Description of the first section', null=True, verbose_name='First Section Description'),
        ),
        migrations.AlterField(
            model_name='bodyworkandpainting',
            name='first_section_description_en',
            field=tinymce.models.HTMLField(blank=True, help_text='Description of the first section', null=True, verbose_name='First Section Description'),
        ),
        migrations.AlterField(
            model_name='carprogramming',
            name='first_section_description',
            field=tinymce.models.HTMLField(blank=True, help_text='Description of the first section', null=True, verbose_name='First Section Description'),
        ),
        migrations.AlterField(
            model_name='carprogramming',
            name='first_section_description_ar',
            field=tinymce.models.HTMLField(blank=True, help_text='Description of the first section', null=True, verbose_name='First Section Description'),
        ),
        migrations.AlterField(
            model_name='carprogramming',
            name='first_section_description_en',
            field=tinymce.models.HTMLField(blank=True, help_text='Description of the first section', null=True, verbose_name='First Section Description'),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='first_section_description',
            field=tinymce.models.HTMLField(blank=True, help_text='Description of the first section', null=True, verbose_name='First Section Description'),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='first_section_description_ar',
            field=tinymce.models.HTMLField(blank=True, help_text='Description of the first section', null=True, verbose_name='First Section Description'),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='first_section_description_en',
            field=tinymce.models.HTMLField(blank=True, help_text='Description of the first section', null=True, verbose_name='First Section Description'),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='image_banner',
            field=models.ImageField(blank=True, help_text='Optional - you can upload an image or leave it blank. <br> If no image is selected, a default image will be displayed.', null=True, upload_to='Our_Services/Electricity/image_banner', verbose_name='Image Banner'),
        ),
        migrations.AlterField(
            model_name='electricityslider',
            name='slider_image',
            field=models.ImageField(blank=True, help_text='Optional - you can upload an image or leave it blank. <br> If no image is selected, a default image will be displayed.', null=True, upload_to='Our_Services/Electricity/slider_image', verbose_name='Slider Image'),
        ),
        migrations.AlterField(
            model_name='mechanics',
            name='first_section_image',
            field=models.ImageField(blank=True, help_text='recommended to use an image with a transparent background.', null=True, upload_to='Our_Services/Mechanics/first_section_image', verbose_name='First Section Image'),
        ),
        migrations.AlterField(
            model_name='mechanics',
            name='image_banner',
            field=models.ImageField(blank=True, help_text='Optional - you can upload an image or leave it blank. <br> If no image is selected, a default image will be displayed.', null=True, upload_to='Our_Services/Mechanics/image_banner', verbose_name='Image Banner'),
        ),
        migrations.AlterField(
            model_name='mechanics',
            name='second_section_image',
            field=models.ImageField(blank=True, help_text='recommended to use an image with a transparent background.', null=True, upload_to='Our_Services/Mechanics/second_section_image', verbose_name='Second Section Image'),
        ),
        migrations.AlterField(
            model_name='mechanicslider',
            name='slider_image',
            field=models.ImageField(blank=True, help_text='Optional - you can upload an image or leave it blank. <br> If no image is selected, a default image will be displayed.', null=True, upload_to='Our_Services/Mechanics/slider_image', verbose_name='Slider Image'),
        ),
        migrations.AlterField(
            model_name='roadsideassistance',
            name='first_section_description',
            field=tinymce.models.HTMLField(blank=True, help_text='Description of the first section', null=True, verbose_name='First Section Description'),
        ),
        migrations.AlterField(
            model_name='roadsideassistance',
            name='first_section_description_ar',
            field=tinymce.models.HTMLField(blank=True, help_text='Description of the first section', null=True, verbose_name='First Section Description'),
        ),
        migrations.AlterField(
            model_name='roadsideassistance',
            name='first_section_description_en',
            field=tinymce.models.HTMLField(blank=True, help_text='Description of the first section', null=True, verbose_name='First Section Description'),
        ),
        migrations.AlterField(
            model_name='sportssuspension',
            name='first_section_description',
            field=tinymce.models.HTMLField(blank=True, help_text='Description of the first section', null=True, verbose_name='First Section Description'),
        ),
        migrations.AlterField(
            model_name='sportssuspension',
            name='first_section_description_ar',
            field=tinymce.models.HTMLField(blank=True, help_text='Description of the first section', null=True, verbose_name='First Section Description'),
        ),
        migrations.AlterField(
            model_name='sportssuspension',
            name='first_section_description_en',
            field=tinymce.models.HTMLField(blank=True, help_text='Description of the first section', null=True, verbose_name='First Section Description'),
        ),
        migrations.AlterField(
            model_name='thermalandsoundinsulation',
            name='first_section_description',
            field=tinymce.models.HTMLField(blank=True, help_text='Description of the first section', null=True, verbose_name='First Section Description'),
        ),
        migrations.AlterField(
            model_name='thermalandsoundinsulation',
            name='first_section_description_ar',
            field=tinymce.models.HTMLField(blank=True, help_text='Description of the first section', null=True, verbose_name='First Section Description'),
        ),
        migrations.AlterField(
            model_name='thermalandsoundinsulation',
            name='first_section_description_en',
            field=tinymce.models.HTMLField(blank=True, help_text='Description of the first section', null=True, verbose_name='First Section Description'),
        ),
    ]
