# Generated by Django 5.1.3 on 2024-11-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان الفرعي')),
                ('vision_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الرؤية')),
                ('vision_text', models.TextField(blank=True, null=True, verbose_name='نص الرؤية')),
                ('goals_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الأهداف')),
                ('goals_list', models.TextField(blank=True, null=True, verbose_name='قائمة الأهداف (كل هدف بسطر)')),
                ('why_us_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان لماذا نحن')),
                ('why_us_points', models.TextField(blank=True, null=True, verbose_name='نقاط لماذا نحن (كل نقطة بسطر)')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='about/images/', verbose_name='الصورة الرئيسية')),
                ('secondary_image', models.ImageField(blank=True, null=True, upload_to='about/images/', verbose_name='الصورة الثانوية')),
                ('shape_image_1', models.ImageField(blank=True, null=True, upload_to='about/shapes/', verbose_name='الصورة الشكلية 1')),
                ('shape_image_2', models.ImageField(blank=True, null=True, upload_to='about/shapes/', verbose_name='الصورة الشكلية 2')),
            ],
            options={
                'verbose_name': 'قسم التعريف',
                'verbose_name_plural': 'أقسام التعريف',
            },
        ),
    ]
