# Generated by Django 5.1.3 on 2024-11-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About_Us', '0002_remove_aboutsection_shape_image_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'verbose_name': 'About Section', 'verbose_name_plural': 'About Sections'},
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='secondary_image',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='first_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/images/', verbose_name='Main Image'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='goals_list_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Goals List (each goal in a line)'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='goals_list_en',
            field=models.TextField(blank=True, null=True, verbose_name='Goals List (each goal in a line)'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='goals_title_ar',
            field=models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='Goals Title'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='goals_title_en',
            field=models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='Goals Title'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='second_picture',
            field=models.ImageField(blank=True, null=True, upload_to='about/images/', verbose_name='Secondary Image'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='sub_title_ar',
            field=models.CharField(blank=True, help_text='Maximum 40 characters', max_length=40, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='sub_title_en',
            field=models.CharField(blank=True, help_text='Maximum 40 characters', max_length=40, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_text_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Vision Text'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Vision Text'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_title_ar',
            field=models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='Vision Title'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_title_en',
            field=models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='Vision Title'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='why_us_points_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Why Us Points (each point in a line)'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='why_us_points_en',
            field=models.TextField(blank=True, null=True, verbose_name='Why Us Points (each point in a line)'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='why_us_title_ar',
            field=models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='Why Us Title'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='why_us_title_en',
            field=models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='Why Us Title'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='goals_list',
            field=models.TextField(blank=True, null=True, verbose_name='Goals List (each goal in a line)'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='goals_title',
            field=models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='Goals Title'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='sub_title',
            field=models.CharField(blank=True, help_text='Maximum 40 characters', max_length=40, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='vision_text',
            field=models.TextField(blank=True, null=True, verbose_name='Vision Text'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='vision_title',
            field=models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='Vision Title'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='why_us_points',
            field=models.TextField(blank=True, null=True, verbose_name='Why Us Points (each point in a line)'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='why_us_title',
            field=models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='Why Us Title'),
        ),
    ]
