# Generated by Django 5.1.3 on 2024-11-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About_Us', '0003_alter_aboutsection_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='second_picture',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/images/', verbose_name='second_image'),
        ),
    ]
