# Generated by Django 5.1.3 on 2024-11-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About_Us', '0004_remove_aboutsection_second_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='first_image',
            field=models.ImageField(blank=True, null=True, upload_to='AboutSection/images/', verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image_banner',
            field=models.ImageField(blank=True, help_text='Optional - you can upload an image or leave it blank. <br> If no image is selected, a default image will be displayed.', null=True, upload_to='AboutSection/image_banner/', verbose_name='Image Banner'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='AboutSection/images/', verbose_name='second_image'),
        ),
    ]
