# Generated by Django 5.1.3 on 2024-12-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='discount_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Discount Value'),
        ),
    ]
