# Generated by Django 5.1.3 on 2024-12-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Service', '0002_appointment_discount_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='discount_amount',
        ),
    ]
