# Generated by Django 5.1.3 on 2024-11-29 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='subtitle')),
                ('subtitle_ar', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='subtitle')),
                ('subtitle_en', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='subtitle')),
                ('title', models.CharField(blank=True, help_text='Maximum characters 40', max_length=40, null=True, verbose_name='title')),
                ('title_ar', models.CharField(blank=True, help_text='Maximum characters 40', max_length=40, null=True, verbose_name='title')),
                ('title_en', models.CharField(blank=True, help_text='Maximum characters 40', max_length=40, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Maximum characters 1000', null=True, verbose_name='description')),
                ('description_ar', models.TextField(blank=True, help_text='Maximum characters 1000', null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, help_text='Maximum characters 1000', null=True, verbose_name='description')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='image_1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='image_2')),
                ('counter_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='counter_value')),
                ('counter_label', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='counter_label')),
                ('counter_label_ar', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='counter_label')),
                ('counter_label_en', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='counter_label')),
                ('counter_icon', models.ImageField(blank=True, help_text='It is better to choose the icon in white color.<br>For icons, visit <a href="https://www.flaticon.com/" target="_blank">https://www.flaticon.com/</a>', null=True, upload_to='about/', verbose_name='counter_icon')),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='experience_years')),
                ('experience_label', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='experience_label')),
                ('experience_label_ar', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='experience_label')),
                ('experience_label_en', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='experience_label')),
                ('experience_icon', models.ImageField(blank=True, help_text='It is better to choose the icon in white color.<br>For icons, visit <a href="https://www.flaticon.com/" target="_blank">https://www.flaticon.com/</a>', null=True, upload_to='about/', verbose_name='experience_icon')),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
            },
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, help_text='Maximum characters 30', max_length=30, null=True, verbose_name='subtitle')),
                ('subtitle_ar', models.CharField(blank=True, help_text='Maximum characters 30', max_length=30, null=True, verbose_name='subtitle')),
                ('subtitle_en', models.CharField(blank=True, help_text='Maximum characters 30', max_length=30, null=True, verbose_name='subtitle')),
                ('title', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title')),
                ('title_ar', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title')),
                ('title_en', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Brands Section',
                'verbose_name_plural': 'Brands Section',
            },
        ),
        migrations.CreateModel(
            name='ChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, help_text='Maximum characters 30', max_length=30, null=True, verbose_name='subtitle')),
                ('subtitle_ar', models.CharField(blank=True, help_text='Maximum characters 30', max_length=30, null=True, verbose_name='subtitle')),
                ('subtitle_en', models.CharField(blank=True, help_text='Maximum characters 30', max_length=30, null=True, verbose_name='subtitle')),
                ('title', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title')),
                ('title_ar', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title')),
                ('title_en', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title')),
            ],
            options={
                'verbose_name': 'ChooseUs Section',
                'verbose_name_plural': 'ChooseUs Section',
            },
        ),
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, help_text='Maximum characters 30', max_length=30, null=True, verbose_name='subtitle')),
                ('subtitle_ar', models.CharField(blank=True, help_text='Maximum characters 30', max_length=30, null=True, verbose_name='subtitle')),
                ('subtitle_en', models.CharField(blank=True, help_text='Maximum characters 30', max_length=30, null=True, verbose_name='subtitle')),
                ('title', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title')),
                ('title_ar', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title')),
                ('title_en', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title')),
                ('image', models.ImageField(blank=True, help_text='Optional image for the FAQ section', null=True, upload_to='faq_section/images/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'FAQ Section',
                'verbose_name_plural': 'FAQ Sections',
            },
        ),
        migrations.CreateModel(
            name='Headers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, help_text='Maximum 30 characters', max_length=30, null=True, verbose_name='Subtitle')),
                ('subtitle_ar', models.CharField(blank=True, help_text='Maximum 30 characters', max_length=30, null=True, verbose_name='Subtitle')),
                ('subtitle_en', models.CharField(blank=True, help_text='Maximum 30 characters', max_length=30, null=True, verbose_name='Subtitle')),
                ('title', models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='Title')),
                ('title_ar', models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='Title')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone Number')),
                ('video_link', models.URLField(blank=True, null=True, verbose_name='Video Link')),
            ],
            options={
                'verbose_name': 'Header',
                'verbose_name_plural': 'Headers',
            },
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='subtitle')),
                ('subtitle_ar', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='subtitle')),
                ('subtitle_en', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='subtitle')),
                ('title', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title')),
                ('title_ar', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title')),
                ('title_en', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Service Section',
                'verbose_name_plural': 'Service Sections',
            },
        ),
        migrations.CreateModel(
            name='SliderSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, help_text='Maximum characters 30', max_length=30, null=True, verbose_name='subtitle')),
                ('subtitle_ar', models.CharField(blank=True, help_text='Maximum characters 30', max_length=30, null=True, verbose_name='subtitle')),
                ('subtitle_en', models.CharField(blank=True, help_text='Maximum characters 30', max_length=30, null=True, verbose_name='subtitle')),
                ('title', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title')),
                ('title_ar', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title')),
                ('title_en', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Slider Section',
                'verbose_name_plural': 'Slider Section',
            },
        ),
        migrations.CreateModel(
            name='WorkSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, help_text='Maximum characters 30', max_length=30, null=True, verbose_name='subtitle')),
                ('subtitle_ar', models.CharField(blank=True, help_text='Maximum characters 30', max_length=30, null=True, verbose_name='subtitle')),
                ('subtitle_en', models.CharField(blank=True, help_text='Maximum characters 30', max_length=30, null=True, verbose_name='subtitle')),
                ('title', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title')),
                ('title_ar', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title')),
                ('title_en', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Work Section',
                'verbose_name_plural': 'Work Sections',
            },
        ),
        migrations.CreateModel(
            name='ChooseUsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='work_card/icons/', verbose_name='Card Icon')),
                ('title', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='Card title')),
                ('title_ar', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='Card title')),
                ('title_en', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='Card title')),
                ('description', models.TextField(blank=True, help_text='Maximum characters 500', max_length=500, null=True, verbose_name='Card Description')),
                ('description_ar', models.TextField(blank=True, help_text='Maximum characters 500', max_length=500, null=True, verbose_name='Card Description')),
                ('description_en', models.TextField(blank=True, help_text='Maximum characters 500', max_length=500, null=True, verbose_name='Card Description')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choose_us_card', to='Home.chooseus')),
            ],
            options={
                'verbose_name': 'ChooseUs Card',
                'verbose_name_plural': 'ChooseUs Cards',
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, help_text='Maximum characters 500', max_length=500, null=True, verbose_name='Question')),
                ('question_ar', models.CharField(blank=True, help_text='Maximum characters 500', max_length=500, null=True, verbose_name='Question')),
                ('question_en', models.CharField(blank=True, help_text='Maximum characters 500', max_length=500, null=True, verbose_name='Question')),
                ('answer', models.TextField(blank=True, help_text='Maximum characters 5000', max_length=5000, null=True, verbose_name='Answer')),
                ('answer_ar', models.TextField(blank=True, help_text='Maximum characters 5000', max_length=5000, null=True, verbose_name='Answer')),
                ('answer_en', models.TextField(blank=True, help_text='Maximum characters 5000', max_length=5000, null=True, verbose_name='Answer')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='Home.faqsection', verbose_name='FAQ Section')),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'FAQ Items',
            },
        ),
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_or_icon', models.ImageField(blank=True, null=True, upload_to='Home_Page/Feature_icon/', verbose_name='image or icon')),
                ('title', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='Title')),
                ('title_ar', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Maximum characters 100', max_length=100, null=True, verbose_name='Description')),
                ('description_ar', models.TextField(blank=True, help_text='Maximum characters 100', max_length=100, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, help_text='Maximum characters 100', max_length=100, null=True, verbose_name='Description')),
                ('heros_lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='Home.headers')),
            ],
            options={
                'verbose_name': 'Feature Item',
                'verbose_name_plural': 'Feature Items',
            },
        ),
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, help_text='Optional - If no image is uploaded, a default image will be used.', null=True, upload_to='Home_Page/background_image/', verbose_name='Background Image')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_images', to='Home.headers')),
            ],
            options={
                'verbose_name': 'Background Image',
                'verbose_name_plural': 'Background Images',
            },
        ),
        migrations.CreateModel(
            name='ImageBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='work_card/icons/', verbose_name='Card Icon')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Home.brands')),
            ],
            options={
                'verbose_name': 'ImageBrand Card',
                'verbose_name_plural': 'ImageBrand Cards',
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_card', models.ImageField(blank=True, null=True, upload_to='work_card/icons/', verbose_name='background_card')),
                ('icon', models.ImageField(blank=True, help_text='For icons, visit <a href="https://www.flaticon.com/" target="_blank">https://www.flaticon.com/</a>', null=True, upload_to='services/icons/')),
                ('title', models.CharField(blank=True, help_text='Maximum characters 30', max_length=30, null=True, verbose_name='title')),
                ('title_ar', models.CharField(blank=True, help_text='Maximum characters 30', max_length=30, null=True, verbose_name='title')),
                ('title_en', models.CharField(blank=True, help_text='Maximum characters 30', max_length=30, null=True, verbose_name='title')),
                ('page_type', models.CharField(choices=[('mechanics', 'Mechanics'), ('electricity', 'Electricity'), ('bodywork_and_painting', 'Bodywork_And_Pinting'), ('thermal_and_soundin_sulation', 'Thermal_And_Soundin_Sulation'), ('car_programming', 'Car_Programming'), ('sports_suspension', 'Sports_Suspension'), ('roadside_assistance', 'Roadside_Assistance')], max_length=100)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_cards', to='Home.servicesection')),
            ],
            options={
                'verbose_name': 'Service Card',
                'verbose_name_plural': 'Service Cards',
            },
        ),
        migrations.CreateModel(
            name='SliderCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='Card title')),
                ('title_ar', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='Card title')),
                ('title_en', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='Card title')),
                ('description', models.TextField(blank=True, help_text='Maximum characters 500', max_length=500, null=True, verbose_name='Card Description')),
                ('description_ar', models.TextField(blank=True, help_text='Maximum characters 500', max_length=500, null=True, verbose_name='Card Description')),
                ('description_en', models.TextField(blank=True, help_text='Maximum characters 500', max_length=500, null=True, verbose_name='Card Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='work_card/icons/', verbose_name='Card Icon')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_card', to='Home.slidersection')),
            ],
            options={
                'verbose_name': 'Slider Card',
                'verbose_name_plural': 'Slider Cards',
            },
        ),
        migrations.CreateModel(
            name='WorkCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='Card title')),
                ('title_ar', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='Card title')),
                ('title_en', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='Card title')),
                ('description', models.TextField(blank=True, help_text='Maximum characters 500', max_length=500, null=True, verbose_name='Card Description')),
                ('description_ar', models.TextField(blank=True, help_text='Maximum characters 500', max_length=500, null=True, verbose_name='Card Description')),
                ('description_en', models.TextField(blank=True, help_text='Maximum characters 500', max_length=500, null=True, verbose_name='Card Description')),
                ('icon', models.ImageField(blank=True, help_text='For icons, visit <a href="https://www.flaticon.com/" target="_blank">https://www.flaticon.com/</a>', null=True, upload_to='work_card/icons/', verbose_name='Card Icon')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='Home.worksection')),
            ],
            options={
                'verbose_name': 'Work Card',
                'verbose_name_plural': 'Work Cards',
            },
        ),
    ]
