# Generated by Django 5.1.3 on 2024-11-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featureitem',
            old_name='heros_lider',
            new_name='header',
        ),
        migrations.RemoveField(
            model_name='featureitem',
            name='image_or_icon',
        ),
        migrations.AddField(
            model_name='featureitem',
            name='icon_or_image',
            field=models.ImageField(blank=True, null=True, upload_to='Home_Page/Feature_icon/', verbose_name='Icon or Image'),
        ),
        migrations.AlterField(
            model_name='featureitem',
            name='description',
            field=models.TextField(blank=True, help_text='Maximum 100 characters', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='featureitem',
            name='description_ar',
            field=models.TextField(blank=True, help_text='Maximum 100 characters', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='featureitem',
            name='description_en',
            field=models.TextField(blank=True, help_text='Maximum 100 characters', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='featureitem',
            name='title',
            field=models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='featureitem',
            name='title_ar',
            field=models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='featureitem',
            name='title_en',
            field=models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='Title'),
        ),
    ]
