# Generated by Django 5.1.3 on 2024-11-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_heros_lider_featureitem_header_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'verbose_name': '2 - About Section', 'verbose_name_plural': '2 - About Sections'},
        ),
        migrations.AlterModelOptions(
            name='headers',
            options={'verbose_name': '1 - Header', 'verbose_name_plural': '1 - Headers'},
        ),
        migrations.AlterModelOptions(
            name='servicesection',
            options={'verbose_name': '4 - Service Section', 'verbose_name_plural': '4 - Service Sections'},
        ),
        migrations.AlterModelOptions(
            name='worksection',
            options={'verbose_name': '3 - Work Section', 'verbose_name_plural': '3 - Work Sections'},
        ),
        migrations.RenameField(
            model_name='servicecard',
            old_name='services',
            new_name='section',
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='counter_icon',
            field=models.ImageField(blank=True, null=True, upload_to='Home_Page/About_Us/', verbose_name='counter_icon'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='counter_label',
            field=models.CharField(blank=True, default='', help_text='Maximum characters 50', max_length=50, verbose_name='counter_label'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Maximum characters 1000', verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='experience_icon',
            field=models.ImageField(blank=True, null=True, upload_to='Home_Page/About_Us/', verbose_name='experience_icon'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='experience_label',
            field=models.CharField(blank=True, default='', help_text='Maximum characters 50', max_length=50, verbose_name='experience_label'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='Home_Page/About_Us/', verbose_name='image_1'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='Home_Page/About_Us/', verbose_name='image_2'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='subtitle',
            field=models.CharField(blank=True, default='', help_text='Maximum characters 50', max_length=50, verbose_name='subtitle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Maximum characters 40', max_length=40, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='Home/SliderSection/'),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='page_type',
            field=models.CharField(choices=[('mechanics', 'Mechanics'), ('electricity', 'Electricity'), ('bodywork_and_painting', 'Bodywork and Painting'), ('thermal_and_soundin_sulation', 'Thermal and Sound Insulation'), ('car_programming', 'Car Programming'), ('sports_suspension', 'Sports Suspension'), ('roadside_assistance', 'Roadside Assistance')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Maximum characters 30', max_length=30, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='title_ar',
            field=models.CharField(blank=True, default='', help_text='Maximum characters 30', max_length=30, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='title_en',
            field=models.CharField(blank=True, default='', help_text='Maximum characters 30', max_length=30, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='workcard',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Maximum characters 1000', max_length=1000, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workcard',
            name='description_ar',
            field=models.TextField(blank=True, help_text='Maximum characters 1000', max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='workcard',
            name='description_en',
            field=models.TextField(blank=True, help_text='Maximum characters 1000', max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='workcard',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='Home/work_card/', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='workcard',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Maximum characters 50', max_length=50, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workcard',
            name='title_ar',
            field=models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='workcard',
            name='title_en',
            field=models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='worksection',
            name='subtitle',
            field=models.CharField(blank=True, default='', help_text='Maximum characters 30', max_length=30, verbose_name='subtitle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worksection',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Maximum characters 50', max_length=50, verbose_name='title'),
            preserve_default=False,
        ),
    ]
