# Generated by Django 5.1.3 on 2024-11-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_aboutsection_options_alter_headers_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqsection',
            options={'verbose_name': '6 - FAQ Section', 'verbose_name_plural': '6 - FAQ Sections'},
        ),
        migrations.AlterModelOptions(
            name='slidersection',
            options={'verbose_name': '5 - Slider Section', 'verbose_name_plural': '5 - Slider Section'},
        ),
        migrations.AlterField(
            model_name='chooseuscard',
            name='description',
            field=models.TextField(blank=True, help_text='Maximum characters 500', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='chooseuscard',
            name='description_ar',
            field=models.TextField(blank=True, help_text='Maximum characters 500', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='chooseuscard',
            name='description_en',
            field=models.TextField(blank=True, help_text='Maximum characters 500', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='chooseuscard',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='work_card/icons/', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='chooseuscard',
            name='title',
            field=models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='chooseuscard',
            name='title_ar',
            field=models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='chooseuscard',
            name='title_en',
            field=models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='faqsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='faq_section/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='imagebrand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='work_card/icons/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='slidercard',
            name='description',
            field=models.TextField(blank=True, help_text='Maximum characters 500', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='slidercard',
            name='description_ar',
            field=models.TextField(blank=True, help_text='Maximum characters 500', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='slidercard',
            name='description_en',
            field=models.TextField(blank=True, help_text='Maximum characters 500', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='slidercard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='work_card/icons/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='slidercard',
            name='title',
            field=models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='slidercard',
            name='title_ar',
            field=models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='slidercard',
            name='title_en',
            field=models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='slidersection',
            name='subtitle',
            field=models.CharField(blank=True, default='', help_text='Maximum characters 30', max_length=30, verbose_name='subtitle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slidersection',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Maximum characters 50', max_length=50, verbose_name='title'),
            preserve_default=False,
        ),
    ]
