# Generated by Django 5.1.3 on 2024-11-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('image', models.ImageField(blank=True, null=True, upload_to='map/images/', verbose_name='Image')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Google Maps URL')),
            ],
            options={
                'verbose_name': 'Map Location',
                'verbose_name_plural': 'Map Locations',
            },
        ),
    ]
