# Generated by Django 5.1.3 on 2024-11-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Our_Center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurCenterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner', models.ImageField(blank=True, help_text='Optional - you can upload an image or leave it blank. <br> If no image is selected, a default image will be displayed.', null=True, upload_to='Our_Services/Thermal_And_Sound_Insulation/image_banner/', verbose_name='Image Banner')),
                ('first_section_title', models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='First Section Title')),
                ('first_section_title_ar', models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='First Section Title')),
                ('first_section_title_en', models.CharField(blank=True, help_text='Maximum 50 characters', max_length=50, null=True, verbose_name='First Section Title')),
                ('first_section_description', models.TextField(blank=True, help_text='Description of the first section', null=True, verbose_name='First Section Description')),
                ('first_section_description_ar', models.TextField(blank=True, help_text='Description of the first section', null=True, verbose_name='First Section Description')),
                ('first_section_description_en', models.TextField(blank=True, help_text='Description of the first section', null=True, verbose_name='First Section Description')),
                ('first_section_image', models.ImageField(blank=True, help_text='Optional - recommended to use an image with a transparent background.', null=True, upload_to='Our_Services/Thermal_And_Sound_Insulation/first_section_image/', verbose_name='First Section Image')),
            ],
            options={
                'verbose_name': 'OurCenter Section',
                'verbose_name_plural': 'MOurCenter Sections',
            },
        ),
        migrations.AddField(
            model_name='maplocation',
            name='address_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='maplocation',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='maplocation',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='maplocation',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='maplocation',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='maplocation',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
