# Generated by Django 5.1.3 on 2024-11-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Our_Center', '0002_ourcentersection_maplocation_address_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMaintenanceCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Specialists Center for Vehicle Maintenance', max_length=255, null=True, verbose_name='عنوان المركز')),
                ('address', models.TextField(blank=True, default='طريق الأمير سعود الفيصل، حي الخالدية البحرية، الدمام، المملكة العربية السعودية. 32540', null=True, verbose_name='العنوان')),
                ('working_hours', models.CharField(blank=True, default='8AM - 7:30PM', max_length=50, null=True, verbose_name='ساعات العمل')),
                ('working_days', models.CharField(blank=True, default='من السبت إلى الخميس', max_length=50, null=True, verbose_name='أيام العمل')),
                ('friday_status', models.CharField(blank=True, default='مغلق', max_length=50, null=True, verbose_name='حالة يوم الجمعة')),
            ],
            options={
                'verbose_name': 'مركز صيانة المركبات',
                'verbose_name_plural': 'مراكز صيانة المركبات',
            },
        ),
    ]
