# Generated by Django 5.1.3 on 2024-11-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Our_Center', '0003_vehiclemaintenancecenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationOurCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Center Title')),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Center Title')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Center Title')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('address_ar', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('address_en', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('working_hours', models.CharField(blank=True, max_length=50, null=True, verbose_name='Working Hours')),
                ('working_days', models.CharField(blank=True, max_length=50, null=True, verbose_name='Working Days')),
                ('working_days_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='Working Days')),
                ('working_days_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Working Days')),
                ('friday_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Friday Status')),
                ('friday_status_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='Friday Status')),
                ('friday_status_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Friday Status')),
            ],
            options={
                'verbose_name': 'Information Our Center',
                'verbose_name_plural': 'Information Our Center ',
            },
        ),
        migrations.DeleteModel(
            name='VehicleMaintenanceCenter',
        ),
        migrations.AlterModelOptions(
            name='ourcentersection',
            options={'verbose_name': 'OurCenter Section', 'verbose_name_plural': 'OurCenter Sections'},
        ),
    ]
