# Generated by Django 5.1.3 on 2024-11-27 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Our_Center', '0004_informationourcenter_delete_vehiclemaintenancecenter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplocation',
            name='section',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Our_Center.informationourcenter', verbose_name='map'),
            preserve_default=False,
        ),
    ]
