# Generated by Django 5.1.3 on 2024-12-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Our_Center', '0005_maplocation_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourcentersection',
            name='first_section_image',
            field=models.ImageField(blank=True, help_text='Optional - recommended to use an image with a transparent background.', null=True, upload_to='OurCenterSection/first_section_image/', verbose_name='First Section Image'),
        ),
        migrations.AlterField(
            model_name='ourcentersection',
            name='image_banner',
            field=models.ImageField(blank=True, help_text='Optional - you can upload an image or leave it blank. <br> If no image is selected, a default image will be displayed.', null=True, upload_to='OurCenterSection/image_banner/', verbose_name='Image Banner'),
        ),
    ]
