# Generated by Django 5.1.3 on 2024-11-28 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'معلومات الاتصال', 'verbose_name_plural': 'معلومات الاتصال'},
        ),
    ]
