# Generated by Django 5.1.3 on 2024-12-02 12:28

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Us', '0002_alter_contactus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterField(
            model_name='contactus',
            name='address',
            field=tinymce.models.HTMLField(verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=tinymce.models.HTMLField(verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=tinymce.models.HTMLField(verbose_name='phone'),
        ),
    ]
