# Generated by Django 5.1.3 on 2024-12-02 12:29

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Us', '0003_alter_contactus_options_alter_contactus_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='address_ar',
            field=tinymce.models.HTMLField(null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='address_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='address'),
        ),
    ]
