# Generated by Django 5.1.3 on 2024-12-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Us', '0004_contactus_address_ar_contactus_address_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='address',
            field=models.TextField(verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='address_ar',
            field=models.TextField(null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='address_en',
            field=models.TextField(null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.PositiveIntegerField(verbose_name='phone'),
        ),
    ]
