# Generated by Django 5.1.3 on 2024-11-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_heros_lider_featureitem_header_and_more'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='PhotoGallery',
        ),
    ]
