# Generated by Django 5.1.3 on 2024-11-27 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title')),
            ],
            options={
                'verbose_name': 'offer Section',
                'verbose_name_plural': ' Sections',
            },
        ),
        migrations.CreateModel(
            name='OfferCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_card', models.ImageField(blank=True, null=True, upload_to='work_card/icons/', verbose_name='background_card')),
                ('title', models.CharField(blank=True, help_text='Maximum characters 30', max_length=30, null=True, verbose_name='title')),
                ('content_one', models.CharField(blank=True, help_text='Maximum characters 100', max_length=100, null=True, verbose_name='content_one')),
                ('content_tow', models.CharField(blank=True, help_text='Maximum characters 100', max_length=100, null=True, verbose_name='content_tow')),
                ('page_type', models.CharField(choices=[('mechanics', 'Mechanics'), ('electricity', 'Electricity'), ('bodywork_and_painting', 'Bodywork_And_Pinting'), ('thermal_and_soundin_sulation', 'Thermal_And_Soundin_Sulation'), ('car_programming', 'Car_Programming'), ('sports_suspension', 'Sports_Suspension'), ('roadside_assistance', 'Roadside_Assistance')], max_length=100)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_cards', to='Our_Offers.offersection')),
            ],
            options={
                'verbose_name': 'offer Card',
                'verbose_name_plural': 'offer Cards',
            },
        ),
    ]
