# Generated by Django 5.1.3 on 2024-11-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Our_Offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offercard',
            name='content_one_ar',
            field=models.CharField(blank=True, help_text='Maximum characters 100', max_length=100, null=True, verbose_name='content_one'),
        ),
        migrations.AddField(
            model_name='offercard',
            name='content_one_en',
            field=models.CharField(blank=True, help_text='Maximum characters 100', max_length=100, null=True, verbose_name='content_one'),
        ),
        migrations.AddField(
            model_name='offercard',
            name='content_tow_ar',
            field=models.CharField(blank=True, help_text='Maximum characters 100', max_length=100, null=True, verbose_name='content_tow'),
        ),
        migrations.AddField(
            model_name='offercard',
            name='content_tow_en',
            field=models.CharField(blank=True, help_text='Maximum characters 100', max_length=100, null=True, verbose_name='content_tow'),
        ),
        migrations.AddField(
            model_name='offercard',
            name='title_ar',
            field=models.CharField(blank=True, help_text='Maximum characters 30', max_length=30, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='offercard',
            name='title_en',
            field=models.CharField(blank=True, help_text='Maximum characters 30', max_length=30, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='offersection',
            name='title_ar',
            field=models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='offersection',
            name='title_en',
            field=models.CharField(blank=True, help_text='Maximum characters 50', max_length=50, null=True, verbose_name='title'),
        ),
    ]
